api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Controller']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            persistAuthorization: true
            docExpansion: 'list'
            deepLinking: true
            tagsSorter: 'alpha'
            defaultModelsExpandDepth: 2
    # Suppression du route_prefix pour éviter la duplication avec le préfix défini dans config/routes/api_platform.yaml